### PR TITLE
added ability to give libvlc initializing options ('--no-xlib' for ex…

### PR DESCRIPTION
**Pull request by passenger94**
…ample) + test

### CODE REVIEW

**Comment by ccoupe** [comment]
which file/script are you using for testing start blocks? OSX needs to test those because it sometimes exhibits different timing/drawing behaviors.

**Comment by passenger94** [comment]
you can use the video test files in Test folders they are perfect for that, i needed to have a look more urgently at start event because of those ones ! (Testing is not yet completely ready, still some threading issue from time to times, - vlc and pulse audio related here -)

**Comment by passenger94** [comment]
for this to work on OSX we need to replace the gtk specific :
https://github.com/Shoes3/shoes3/blob/master/shoes/canvas.c#L1852
with the osx equivalent, looks like it should be something like :
https://github.com/Shoes3/shoes3/blob/master/shoes/native/cocoa.m#L596

either by means of ifdef, or creating clean native methods for this
would be cool, before the 3.3.1 release, is it possible ?

**Comment by ccoupe** [comment]
Everything is possible. I'd like to get my Windows font fixes into 3.3.1 too.  I'll make some new betas and announce those with a note that a couple more features/fixes will show up in the released.

**Comment by passenger94** [comment]
yeah, no hurry :-)
as you were about to release, i thought about a reminder that this feature is not complete 

Also tests are not working on Windows because of some threading issue between tests and shoes and vlc (lots of people in there ...) only the tests are problematic

**Comment by ccoupe** [comment]
Windows ruby and gtk  differences of opinion of how to implement select and poll on windows (simulated file descriptors).  I think I used Ruby fd's instead of gtk/glib/mingw.  We are lucky it works at all (and those compiler warnings are hard to silence on Windows).  Windows does not have native pthreads either so those have to be simulated and there can be different libraries involved in that.  Sorting it out is quite difficult.

**Comment by passenger94** [comment]
Ok, i came up with something working on both platforms.
This time i keep everything gui related exclusively in Shoes, and call test unit when shoes is ready, .... ... which make sense !!! :rotating_light:     No more Threads ! 
Don't mix ruby threads in Shoes gui business ! is something i need to remember.

Glib has all sorts of cabalistic Ancient Woodoo invocations for Threading witchcraft, would it be reasonable to bring to Shoes some threading facilities - all we have right now are Timers - ? (don't know what is the situation on OSX)

**Comment by ccoupe** [comment]
gtk lore is rife with warnings to not update the gui in new threads.  and that applies to Ruby threads and even more so on Windows. 

I don't see much fun in trying to introduce Shoes specific thread abilities unless someone is willing to rewrite Ruby/w32 to use gtk/glib threads (and gio?) which would be a massive task to be maintained forever.  Maybe something like a Shoes method/verb` do_in_gui(&blk)` which just asking for trouble.

**Pull request merged**
