### PR TITLE
fix for #151 + revert to fix for bug in rvm

### PR DESCRIPTION
**Pull request by passenger94**

### CODE REVIEW

**Comment by ccoupe** [comment]
Thanks.

**Comment by ccoupe** [comment]
Something is wrong. I pulled it to my system and git says i'm up-to-date but the files did not change.

**Comment by passenger94** [comment]
? looks ok, in federales branch that is

**Comment by ccoupe** [comment]
Ah, but we're working on master branch. federales is just a place holder. Good thing it's a small patch.

**Comment by ccoupe** [comment]
The fix didn't make to local federales copy either but its clearly on github/federales. I know it downloaded something.  Looking in .git I see FETCH_HEAD with 3 lines - first is marked branch 'master' OK. 2nd line is "not-for-merge	branch 'federales'"  which might explain things. 
Third line is marked "not-for-merge 	branch 'gtk3'"

I think that  is correct for gtk3 - as the gtk3 code was merged into master.  Since I don't intend to release any new in Federales that setting is probably correct.  Now would be a good time to see I can force a merge just in case I really need to update Federales.

**Pull request merged**
