### PR TITLE
fix for image paths in manual examples

### PR DESCRIPTION
**Pull request by passenger94**
The paths for images loaded from disk in manual examples were wrong
(added DIR constant to paths)
- @ccoupe my commit added your last commit on manual, don't know why ...

### CODE REVIEW

**Comment by ccoupe** [comment]
@passenger94 - you're patch reverted my changes. I don't why either.

**Comment by passenger94** [comment]
ouch ! there is a going back feature, right ?

**Comment by ccoupe** [comment]
There is a revert button. Which would remove your changes. Which we would have to put back in. I'll do that later today.

**Comment by passenger94** [comment]
pull request with corrections :-)

**Pull request merged**
