### PR TITLE
cleaning + good-svgview.rb and corrected paris.svg

### PR DESCRIPTION
**Pull request by passenger94**

### CODE REVIEW

**Comment by BackOrder** [comment]
What are the corrections (and what for) in paris.svg?

**Comment by passenger94** [comment]
short story : 
**librsvg** is confused by **some** (not all) kinds of template placements (i'm calling "template" a group that end up in *"def"* section of an svg file, then cloned away in an actual visible group, by *use* directive),
anyway librsvg reports whimsical dimensions and offsets, making Shoes unable to do proper placement ...

basically i resetted matrices to origin and put back objects in place (apparently Inkscape is not the better tool at this)
This corrected file is only to be used as a demo for good-svgview.rb, showing Shoes behavior with a file that librsvg sees as correct ...

if it tells you something, problematic bits were always letters or numbers at the bottom-right or top-left corners, but not all of them, for example all kings, all jacks, 10s ..., jokers (the symbols, for them)

**Comment by BackOrder** [comment]
Will your tool to correct svg included along the ride? This could be a worthwhile tool to ensure compatibility with svg downloaded from the Internet.

**Comment by passenger94** [comment]
I used Inkscape, but it was a pain for that task ...

**Comment by BackOrder** [comment]
Then a procedure should be documented on the wiki.

**Pull request merged**
